# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: battleground.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protos.python.character_pb2 as character__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='battleground.proto',
  package='battleground',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x62\x61ttleground.proto\x12\x0c\x62\x61ttleground\x1a\x0f\x63haracter.proto\"n\n\x13\x42\x61ttlegroundRequest\x12*\n\x0c\x66irst_player\x18\x01 \x01(\x0b\x32\x14.character.Character\x12+\n\rsecond_player\x18\x02 \x01(\x0b\x32\x14.character.Character\"i\n\x14\x42\x61ttlegroundResponse\x12$\n\x06winner\x18\x01 \x01(\x0b\x32\x14.character.Character\x12+\n\nbattle_log\x18\x02 \x03(\x0b\x32\x17.battleground.BattleLog\"\xa6\x01\n\tBattleLog\x12&\n\x08\x61ttacker\x18\x01 \x01(\x0b\x32\x14.character.Character\x12&\n\x08\x64\x65\x66\x65nder\x18\x02 \x01(\x0b\x32\x14.character.Character\x12\x0e\n\x06\x64\x61mage\x18\x03 \x01(\x05\x12\x16\n\x0e\x64\x65\x66\x65nce_health\x18\x04 \x01(\x05\x12!\n\x06skills\x18\x05 \x03(\x0b\x32\x11.character.Skills2h\n\x13\x42\x61ttlegroundService\x12Q\n\x08\x46ighting\x12!.battleground.BattlegroundRequest\x1a\".battleground.BattlegroundResponseb\x06proto3')
  ,
  dependencies=[character__pb2.DESCRIPTOR,])




_BATTLEGROUNDREQUEST = _descriptor.Descriptor(
  name='BattlegroundRequest',
  full_name='battleground.BattlegroundRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_player', full_name='battleground.BattlegroundRequest.first_player', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='second_player', full_name='battleground.BattlegroundRequest.second_player', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=163,
)


_BATTLEGROUNDRESPONSE = _descriptor.Descriptor(
  name='BattlegroundResponse',
  full_name='battleground.BattlegroundResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='winner', full_name='battleground.BattlegroundResponse.winner', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='battle_log', full_name='battleground.BattlegroundResponse.battle_log', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=270,
)


_BATTLELOG = _descriptor.Descriptor(
  name='BattleLog',
  full_name='battleground.BattleLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attacker', full_name='battleground.BattleLog.attacker', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='defender', full_name='battleground.BattleLog.defender', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='damage', full_name='battleground.BattleLog.damage', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='defence_health', full_name='battleground.BattleLog.defence_health', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skills', full_name='battleground.BattleLog.skills', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=439,
)

_BATTLEGROUNDREQUEST.fields_by_name['first_player'].message_type = character__pb2._CHARACTER
_BATTLEGROUNDREQUEST.fields_by_name['second_player'].message_type = character__pb2._CHARACTER
_BATTLEGROUNDRESPONSE.fields_by_name['winner'].message_type = character__pb2._CHARACTER
_BATTLEGROUNDRESPONSE.fields_by_name['battle_log'].message_type = _BATTLELOG
_BATTLELOG.fields_by_name['attacker'].message_type = character__pb2._CHARACTER
_BATTLELOG.fields_by_name['defender'].message_type = character__pb2._CHARACTER
_BATTLELOG.fields_by_name['skills'].message_type = character__pb2._SKILLS
DESCRIPTOR.message_types_by_name['BattlegroundRequest'] = _BATTLEGROUNDREQUEST
DESCRIPTOR.message_types_by_name['BattlegroundResponse'] = _BATTLEGROUNDRESPONSE
DESCRIPTOR.message_types_by_name['BattleLog'] = _BATTLELOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BattlegroundRequest = _reflection.GeneratedProtocolMessageType('BattlegroundRequest', (_message.Message,), {
  'DESCRIPTOR' : _BATTLEGROUNDREQUEST,
  '__module__' : 'battleground_pb2'
  # @@protoc_insertion_point(class_scope:battleground.BattlegroundRequest)
  })
_sym_db.RegisterMessage(BattlegroundRequest)

BattlegroundResponse = _reflection.GeneratedProtocolMessageType('BattlegroundResponse', (_message.Message,), {
  'DESCRIPTOR' : _BATTLEGROUNDRESPONSE,
  '__module__' : 'battleground_pb2'
  # @@protoc_insertion_point(class_scope:battleground.BattlegroundResponse)
  })
_sym_db.RegisterMessage(BattlegroundResponse)

BattleLog = _reflection.GeneratedProtocolMessageType('BattleLog', (_message.Message,), {
  'DESCRIPTOR' : _BATTLELOG,
  '__module__' : 'battleground_pb2'
  # @@protoc_insertion_point(class_scope:battleground.BattleLog)
  })
_sym_db.RegisterMessage(BattleLog)



_BATTLEGROUNDSERVICE = _descriptor.ServiceDescriptor(
  name='BattlegroundService',
  full_name='battleground.BattlegroundService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=441,
  serialized_end=545,
  methods=[
  _descriptor.MethodDescriptor(
    name='Fighting',
    full_name='battleground.BattlegroundService.Fighting',
    index=0,
    containing_service=None,
    input_type=_BATTLEGROUNDREQUEST,
    output_type=_BATTLEGROUNDRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BATTLEGROUNDSERVICE)

DESCRIPTOR.services_by_name['BattlegroundService'] = _BATTLEGROUNDSERVICE

# @@protoc_insertion_point(module_scope)
