# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protos.python.battleground_pb2 as battleground__pb2


class BattlegroundServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Fighting = channel.unary_unary(
        '/battleground.BattlegroundService/Fighting',
        request_serializer=battleground__pb2.BattlegroundRequest.SerializeToString,
        response_deserializer=battleground__pb2.BattlegroundResponse.FromString,
        )


class BattlegroundServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Fighting(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BattlegroundServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Fighting': grpc.unary_unary_rpc_method_handler(
          servicer.Fighting,
          request_deserializer=battleground__pb2.BattlegroundRequest.FromString,
          response_serializer=battleground__pb2.BattlegroundResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'battleground.BattlegroundService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
